# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
sudo: false
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - node_modules
